import { Socket } from 'socket.io';
import logger from '../../config/logger';

interface AuthenticatedSocket extends Socket {
  user: {
    id: string;
    email: string;
    role: string;
  };
}

export interface AgentStatus {
  agentId: string;
  agentType: 'SCRIBE' | 'PRESCRIPTION' | 'REFERRAL' | 'APPOINTMENT' | 'SUPERVISOR';
  status: 'IDLE' | 'PROCESSING' | 'COMPLETED' | 'ERROR';
  progress?: number;
  message?: string;
  result?: any;
}

export const handleAgentEvents = (socket: AuthenticatedSocket, io: any) => {
  /**
   * Update agent status
   */
  socket.on(
    'agent:status-update',
    (data: {
      consultationId: string;
      agentStatus: AgentStatus;
    }) => {
      try {
        const { consultationId, agentStatus } = data;

        logger.info(
          `Agent ${agentStatus.agentId} status: ${agentStatus.status} for consultation ${consultationId}`
        );

        // Broadcast agent status to all participants in the consultation room
        io.to(`consultation:${consultationId}`).emit('agent:status:updated', {
          consultationId,
          agentStatus,
          timestamp: new Date(),
        });
      } catch (error: any) {
        logger.error('Error updating agent status:', error);
        socket.emit('agent:error', {
          message: error.message || 'Failed to update agent status',
        });
      }
    }
  );

  /**
   * Request agent status
   */
  socket.on(
    'agent:get-status',
    (data: {
      consultationId: string;
      agentId?: string;
    }) => {
      try {
        const { consultationId, agentId } = data;

        // TODO: Implement agent status retrieval from a status store
        logger.info(
          `Agent status requested for consultation ${consultationId}${agentId ? `, agent ${agentId}` : ''}`
        );

        socket.emit('agent:status:response', {
          consultationId,
          agentId,
          // Placeholder response
          status: 'IDLE',
        });
      } catch (error: any) {
        logger.error('Error getting agent status:', error);
        socket.emit('agent:error', {
          message: error.message || 'Failed to get agent status',
        });
      }
    }
  );

  /**
   * Trigger agent processing
   */
  socket.on(
    'agent:trigger',
    (data: {
      consultationId: string;
      agentType: AgentStatus['agentType'];
    }) => {
      try {
        const { consultationId, agentType } = data;

        logger.info(
          `Agent ${agentType} triggered for consultation ${consultationId} by ${socket.user.email}`
        );

        // TODO: Implement agent triggering logic
        // This would typically start the agent processing pipeline

        // Acknowledge trigger
        socket.emit('agent:triggered', {
          consultationId,
          agentType,
          timestamp: new Date(),
        });

        // Broadcast to consultation room
        io.to(`consultation:${consultationId}`).emit('agent:started', {
          consultationId,
          agentType,
          triggeredBy: socket.user.id,
        });
      } catch (error: any) {
        logger.error('Error triggering agent:', error);
        socket.emit('agent:error', {
          message: error.message || 'Failed to trigger agent',
        });
      }
    }
  );

  /**
   * Document generated by agent
   */
  socket.on(
    'agent:document-generated',
    (data: {
      consultationId: string;
      documentType: 'SOAP' | 'PRESCRIPTION' | 'REFERRAL' | 'APPOINTMENT';
      document: any;
    }) => {
      try {
        const { consultationId, documentType, document } = data;

        logger.info(
          `${documentType} document generated for consultation ${consultationId}`
        );

        // Broadcast to all participants
        io.to(`consultation:${consultationId}`).emit('document:generated', {
          consultationId,
          documentType,
          document,
          timestamp: new Date(),
        });
      } catch (error: any) {
        logger.error('Error broadcasting document generation:', error);
        socket.emit('agent:error', {
          message: error.message || 'Failed to broadcast document',
        });
      }
    }
  );

  /**
   * Agent error notification
   */
  socket.on(
    'agent:error-report',
    (data: {
      consultationId: string;
      agentId: string;
      error: string;
    }) => {
      try {
        const { consultationId, agentId, error } = data;

        logger.error(
          `Agent ${agentId} error for consultation ${consultationId}: ${error}`
        );

        // Broadcast error to consultation room
        io.to(`consultation:${consultationId}`).emit('agent:error:broadcast', {
          consultationId,
          agentId,
          error,
          timestamp: new Date(),
        });
      } catch (error: any) {
        logger.error('Error reporting agent error:', error);
      }
    }
  );
};

// Made with Bob